version: "2"

services:
  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php
    entrypoint:
      - php-fpm
    environment:
      DEBUG: 'true'
    working_dir: /var/www/
    volumes:
      - ./back-end/:/var/www/
  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front-end/dist/front-end:/usr/share/nginx/html
    ports:
      - 81:81